const employees = [
  {
    id: 1,
    firstName: 'Rahul',
    avatar: 'https://i.pravatar.cc/150?img=11',
    email: 'employee1@example.com',
    password: '123',
    taskNumbers: {
      total: 3,
      active: 2,
      newtask: 1,
      complete: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: 'Prepare report',
        taskDescription: 'Prepare monthly sales report',
        taskDate: '2025-01-05',
        active: true,
        newtask: true,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Client follow-up',
        taskDescription: 'Follow up with pending clients',
        taskDate: '2025-01-07',
        active: true,
        newtask: false,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Update CRM',
        taskDescription: 'Update customer records in CRM',
        taskDate: '2025-01-10',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: 'Amit',
    avatar: 'https://i.pravatar.cc/150?img=12',
    email: 'employee2@example.com',
    password: '123',
    taskNumbers: {
      total: 4,
      active: 2,
      newtask: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: 'Design banner',
        taskDescription: 'Create marketing banner for campaign',
        taskDate: '2025-01-06',
        active: true,
        newtask: true,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Social media post',
        taskDescription: 'Schedule posts for Instagram',
        taskDate: '2025-01-08',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
      {
        taskTitle: 'Fix UI bug',
        taskDescription: 'Resolve navbar responsiveness issue',
        taskDate: '2025-01-09',
        active: false,
        newtask: false,
        complete: false,
        failed: true,
      },
      {
        taskTitle: 'Team meeting',
        taskDescription: 'Attend weekly team sync',
        taskDate: '2025-01-11',
        active: true,
        newtask: false,
        complete: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: 'Suresh',
    avatar: 'https://i.pravatar.cc/150?img=13',
    email: 'employee3@example.com',
    password: '123',
    taskNumbers: {
      total: 3,
      active: 1,
      newtask: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: 'API integration',
        taskDescription: 'Integrate payment gateway API',
        taskDate: '2025-01-04',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
      {
        taskTitle: 'Write documentation',
        taskDescription: 'Document API endpoints',
        taskDate: '2025-01-06',
        active: true,
        newtask: true,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Bug fixing',
        taskDescription: 'Fix login authentication issue',
        taskDate: '2025-01-08',
        active: false,
        newtask: false,
        complete: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    firstName: 'Vikas',
    avatar: 'https://i.pravatar.cc/150?img=14',
    email: 'employee4@example.com',
    password: '123',
    taskNumbers: {
      total: 4,
      active: 2,
      newtask: 1,
      complete: 2,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: 'Testing',
        taskDescription: 'Perform unit testing',
        taskDate: '2025-01-03',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
      {
        taskTitle: 'Regression test',
        taskDescription: 'Test old features after update',
        taskDate: '2025-01-05',
        active: true,
        newtask: true,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Bug report',
        taskDescription: 'Create detailed bug report',
        taskDate: '2025-01-07',
        active: true,
        newtask: false,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Automation script',
        taskDescription: 'Write automation test script',
        taskDate: '2025-01-10',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: 'Rohit',
    avatar:
      'https://unsplash.com/photos/a-man-with-a-red-hoodie-is-standing-in-front-of-a-white-background-9L5KQwOtRrQ',
    email: 'employee5@example.com',
    password: '123',
    taskNumbers: {
      total: 5,
      active: 2,
      newtask: 1,
      complete: 2,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: 'Database backup',
        taskDescription: 'Take weekly database backup',
        taskDate: '2025-01-02',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
      {
        taskTitle: 'Optimize query',
        taskDescription: 'Improve slow SQL queries',
        taskDate: '2025-01-06',
        active: true,
        newtask: true,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Server monitoring',
        taskDescription: 'Monitor server performance',
        taskDate: '2025-01-09',
        active: true,
        newtask: false,
        complete: false,
        failed: false,
      },
      {
        taskTitle: 'Security patch',
        taskDescription: 'Apply latest security patches',
        taskDate: '2025-01-12',
        active: false,
        newtask: false,
        complete: false,
        failed: true,
      },
      {
        taskTitle: 'Log cleanup',
        taskDescription: 'Remove old server logs',
        taskDate: '2025-01-14',
        active: false,
        newtask: false,
        complete: true,
        failed: false,
      },
    ],
  },
]

const admin = [
  {
    id: 1,
    firstName: 'Ankit',
    avatar: 'https://i.pravatar.cc/150?img=16',
    email: 'admin@example.com',
    password: '123',
  },
]

export const setLocalStorage = () => {
  // Deprecated: Logic moved to specific storage utils (adminStorage/employeeStorage) to prevent overwriting data.
}

export const getLocalStorage = (key) => {
  const data = localStorage.getItem(key)
  return data ? JSON.parse(data) : null
}
